spring:
  profiles:
    active:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/sp2}
    username: ${POSTGRE_USER:postgres}
    password: ${POSTGRE_PASSWORD:292004nhan}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    hibernate:
      ddl-auto: none
  sendgrid:
    api-key: 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
    from-email: nhanbh1004@gmail.com


server:
  port: 80

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    title: Sp2 document
    version: v1.0.0
    server: http://localhost:${server.port}
